### ISSUE TITLE
seeder skips columns with legitimate "0" values

### ISSUE THREAD

**Issue by marekr** [Flynsarmy/laravel-csv-seeder#10]
CSV file has "0"s intermixed in one column

One bit of logic is this in the csvseeder class

					foreach ($header as $key) {
						if (!empty($row[$i])) {
							$row_values[$key] = $row[$i];
						}
						$i++;
					}

php will evaluate empty() on the 0 and return true. So things become problematic when you really want the value to be zero. Ideally it shouldn't care about whether its a blank string or not and should just be a isset check to ensure the array element exists at all(proper number of columns read in row).

**Comment by Flynsarmy** [comment]
Sorry I thought I commented on this. This was solved in #9
