### ISSUE TITLE
Not all entries make it into the database.

### ISSUE THREAD

**Issue by Shobs** [Flynsarmy/laravel-csv-seeder#13]
Hello,

I am having a bit of an issue importing a csv full of email addresses.

As per your example here is the code I am using:

    public function __construct()
    {
        $this->table = 'users';
        $this->csv_delimiter = '|';
        $this->filename = base_path().'/database/seeds/csvs/list.csv';
        $this->mapping = [
            0=> 'email',
            1 => 'language'
        ];
    }

    public function run()
    {
        // Recommended when importing larger CSVs
        DB::disableQueryLog();

        // Uncomment the below to wipe the table clean before populating
        DB::table($this->table)->truncate();

        parent::run();
    }

My CSV looks something like this:

someemailaddress@HOTMAIL.COM|nl
anotheremailaddress@gmail.com|en
nospamplz@yahoo.com|fr
...

I originally have 11033 entries in the csv, but after the import only 8883 make it, and if I use the the insert_chunk_size option I only get a little over 5000 entries.

I have noticed that there seems to be rows that don't make it or get deleted since the end id of the last row does match the number of entries, i.e. row 8883 in mysql has ID 11033

For example in the table the ids jump from 7550 -> 7701 from one row to the next.  i.e

id | email | language
------------ | ------------- | -------------
7550 | someemail@dkdk.com | en
7701 | testemail@toto.com      | fr 

Thanks for the plugin!

**Comment by Flynsarmy** [comment]
The package will [log SQL errors](https://github.com/Flynsarmy/laravel-csv-seeder/blob/master/src/Flynsarmy/CsvSeeder/CsvSeeder.php#L235). Check your log to see what went wrong.

**Comment by Shobs** [comment]
Thanks for pointing me in the right direction.

I ended up having duplicate emails in a unique field.  Once I sorted through the .CSV for duplicate everything worked as intended.

Thanks for a great package that saved me A LOT of time :)

**Comment by Flynsarmy** [comment]
No prob :)
