### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by reinhardp** [Flynsarmy/laravel-csv-seeder#18]
Hello,

What about comments in csv files?  
eg  I have this csv file:

St. James the Greater;2016-07-25;true;false;true
# An comment
Constitution Day;2016-12-06;true;false;true
National Holiday;2016-03-13;true;false;true #Vatikan

What I mean is that all lines after # should be ignored.

**Comment by Flynsarmy** [comment]
The CSV standard doesn't support comments. Implementing your suggestion
could have unintended consequences on imports.

**Comment by reinhardp** [comment]
Thank you for your answer.

I have an other question:
My requirement is that if a user login he can see all text in his 
selected language. And he can also search in his selected language.

e.g.
1) user login. (he has a stored language.) Than the language have to be 
changed to this language for all blade templates.

2) the user changes his language in his profile the language have to be 
changed.

As I understand your package this is not possible.

regards,
Reinhard.
P.S: sorry for my bad english. I am a native german.



Am 23.09.2016 um 08:47 schrieb Flynsarmy:
> The CSV standard doesn't support comments. Implementing your suggestion
> could have unintended consequences on imports.
>

**Comment by Flynsarmy** [comment]
My package has no frontend. Importing is entirely behind the scenes. You
can make your site look like anything you want.

**Comment by reinhardp** [comment]
I am sorry for the late answer. Your package is very great! I like it for some importing of CSV files.

best regards,
Reinhard
