### ISSUE TITLE
Mutiple Table and CSV

### ISSUE THREAD

**Issue by laet4x** [Flynsarmy/laravel-csv-seeder#21]
I would like to ask how to populate multiple tables with every csv.
For example 

 $this->table = 'table_1';
 $this->filename = base_path().'/database/seeds/csvs/table1.csv';

 $this->table = 'table_2';
 $this->filename = base_path().'/database/seeds/csvs/table2.csv';

**Comment by Flynsarmy** [comment]
```php
$tables = ['table1', 'table2', 'table3'];

foreach ($tables as $table) {
    $seeder = new \Flynsarmy\CsvSeeder\CsvSeeder;
    $seeder->table = $table;
    $seeder->filename = __DIR__."/csvs/$table.csv";
    $seeder->run();
}
```
