### ISSUE TITLE
Export from Excel on Mac needs to export as Windows CSV

### ISSUE THREAD

**Issue by PaulLawton227** [Flynsarmy/laravel-csv-seeder#24]
Exporting from a Mac using Comma Separated File save causes it to only process the first row of the CSV (I think due to the end of line delimiters only having \r and not \r\n) - for it to work , you have to export as a Windows Comma Separated csv file.

**Comment by Flynsarmy** [comment]
You might be able to set `ini_set("auto_detect_line_endings", true);` before calling `run()` to fix this. I haven't tested.
