### ISSUE TITLE
Add a function for insert.

### ISSUE THREAD

**Issue by cgmerida** [Flynsarmy/laravel-csv-seeder#26]
I have an excel of users and an excel of addresses with the user full name, how I can seed the database converting the full name into the ID of the users?

where can I add a function that queries the id of the user with the name?

**Comment by Flynsarmy** [comment]
Hmm, this package may not be for you. In the interests of simplicity and speed, all this package does is map CSV rows to DB columns and does a chunked `INSERT` statement.

You could create two tables - `imported_users` and `imported_addresses` then after calling `$seeder->run()` do your SQL query merging the data into your `users` table I suppose.
