### ISSUE TITLE
Syntax error  at CsvSeeder.php:22

### ISSUE THREAD

**Issue by mrshoikot** [Flynsarmy/laravel-csv-seeder#30]
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

  at C:\xampp\htdocs\docstasapp\vendor\flynsarmy\csv-seeder\src\Flynsarmy\CsvSeeder\CsvSeeder.php:22
    18|      * DB table name
    19|      *
    20|      * @var string
    21|      */
  > 22|     public string $table = '';
    23|
    24|     /**
    25|      * CSV filename
    26|      *

**Comment by Flynsarmy** [comment]
This package now requirea PHP7.4
