### ISSUE TITLE
FatalThrowableError  : syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by mcfoi** [Flynsarmy/laravel-csv-seeder#31]
I am using Php 7.2, Laravel 6.18 and i chacked against 2.0.0->2.0.2 versions and I am always getting this error even if I have an almost empty CsvSeeder

```
Symfony\Component\Debug\Exception\FatalThrowableError  : syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

  at /var/www/vendor/flynsarmy/csv-seeder/src/Flynsarmy/CsvSeeder/CsvSeeder.php:22
    18|      * DB table name
    19|      *
    20|      * @var string
    21|      */
    22|     public string $table;
    23|
    24|     /**
    25|      * CSV filename
    26|      *

```
```
  Exception trace:

  1   Composer\Autoload\includeFile("/var/www/vendor/composer/../flynsarmy/csv-seeder/src/Flynsarmy/CsvSeeder/CsvSeeder.php")
      /var/www/vendor/composer/ClassLoader.php:322
  2   Composer\Autoload\ClassLoader::loadClass("Flynsarmy\CsvSeeder\CsvSeeder")
      [internal]:0
...
```
This is the CsvSeeder:

```
<?php
use Flynsarmy\CsvSeeder\CsvSeeder;
class Comuni201901Seeder extends CsvSeeder
{
    public function __construct()
    {
        $this->table = 'comuni201901s';
        //$this->csv_delimiter = ',';
        $this->filename = base_path().'/database/seeds/csv/comuni_2019_01.csv';
        //$this->should_trim = true;
    }

    public function run()
    {
        // Recommended when importing larger CSVs
        DB::disableQueryLog();
        // Uncomment the below to wipe the table clean before populating
        //DB::table($this->table)->truncate();
        //parent::run();
    }
}
```

**Comment by Flynsarmy** [comment]
Version 2 requires PHP 7.4 as per https://github.com/Flynsarmy/laravel-csv-seeder/blob/master/composer.json#L13

**Comment by mcfoi** [comment]
Ok.. ..that's an explanation! V.2.0.0 seemed to require just PHP "7".. ..so my 7.2 looked fine.
Anyway I feel the choice was a bit too extreme.. ..as PHP 7.4 is still not so mainstream on mid-range shared hosts. Thanks anyway for you nice and useful tool!

**Comment by Flynsarmy** [comment]
That may be so. I was pretty much just following in spaties footsteps who did the same with their whole inventory a few weeks back and personally prefer coding with the types defined. 

If you look at this projects forks, someone made a 7.2 compatible version. It's unknown if he'll continue to maintain it but it's there if you want it.

**Comment by mcfoi** [comment]
Thank you! I'll check it.
I currently reverted to v.1.0.7 that despite being still for PHP 5.6, is still working perfectly with PHP 7.2

**Comment by mostafakram** [comment]
@Flynsarmy could you please mention this on the readme 

let developers know what package version they should choose with php version

**Comment by Flynsarmy** [comment]
Sure thing. PRs are accepted :)
