### ISSUE TITLE
make Hash work for Lumen

### ISSUE THREAD

**Issue by ab-kily** [Flynsarmy/laravel-csv-seeder#33]
Hello and thank you for such a great plugin! 

I'm experiencing problem trying to use your plugin in Lumen enviroment. I have the following seeder:
```php
<?php
  
use Flynsarmy\CsvSeeder\CsvSeeder;

class UserSeeder extends CsvSeeder
{   
    public function __construct()
    {
        $this->table = 'user';
        $this->csv_delimiter = "\t";
        $this->filename = base_path().'/database/seeds/csv/user.csv';
        $this->should_trim = true;
    }

    public function run()
    {
        parent::run();
    }
}
```

When i run *./artisan db:seed --class=UserSeeder* i get the following:
```bash
# ./artisan db:seed --class=UserSeeder

In CsvSeeder.php line 286:
                          
  Class 'Hash' not found  
                          
```
I don't have mush experience with Laravel framework, but it seems to me *Hash* namespace is only available in Laravel framework and IS NOT available in Lumen framework. 

Isn't it better to change "use" directive in file CsvSeeder.php from:
```php
use Hash;
``` 
to 
```php
use Illuminate\Support\Facades\Hash;
```
? When I change CsvSeeder.php to use Illuminate\Support\Facades\Hash everything works fine in Lument enviroment:
```bash
# ./artisan db:seed --class=UserSeeder
Database seeding completed successfully.
```

**Comment by Flynsarmy** [comment]
Fixed. Thanks for the detailed writeup.
