### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sinnbeck** [Flynsarmy/laravel-csv-seeder#38]
Any chance you would want to do a new release? I am currently stuck as I am in need of this fix :)

https://github.com/Flynsarmy/laravel-csv-seeder/commit/4f50c9d36ffc550f3eda94bd74a78d1a70823c79

I will gladly help anyway I can.

**Comment by Flynsarmy** [comment]
Done! https://github.com/Flynsarmy/laravel-csv-seeder/releases/tag/v2.0.6

**Comment by sinnbeck** [comment]
Thank you so much! I really appreciate it. This package is such a nice piece of work and was exactly what I needed to handle a tricky seeder problem with an mssql database
