### ISSUE TITLE
Multiple Inserts being broken

### ISSUE THREAD

**Issue by ragingdave** [Flynsarmy/laravel-csv-seeder#6]
While using this I think I found a bug.  When data in the csv file sometimes has certain fields, https://github.com/Flynsarmy/laravel-csv-seeder/blob/master/src/Flynsarmy/CsvSeeder/CsvSeeder.php#L107 seems to break the inserts at least on laravel 4.2.
I get many errors unless I make the insert_chunk_size = 1.

**Comment by Flynsarmy** [comment]
On laravel 5.1 with the example code bulk inserts are working fine. Unless you can provide a set of replicatable steps to produce your error, I'm closing this issue.

**Comment by hassanalami** [comment]
i got the same issue with this file: https://gist.github.com/hassanalami/d7142b15fb3e587d61a406ab2ab68ee2
the line:
38010;ANNOISIN CHATELANS;38460;ANNOISIN CHATELANS;;45.7607896686, 5.29198081726
is not inserted unless the insert_chunk_size is set to 1
